sudo: required

language: go

services:
  - docker

script:
- go test .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build .
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push iljich/fmbot;
    fi
