sudo: required

language: go

services:
  - docker

env:
  global:
    secure: "o916o4oJYL+0VCXVbDW/BBSt1LnD4w/Vfem8XJ0UVIGitLJJQfPKkYbVS0Xr3sLYYyfcliftJLM0zJ3nCLJ8mLzTaLJSbf9fVytEItil+G2TqOzEscohGyqmZbm835EmN3r2j6RU7t2FnDQ9tkjL/C907JibIJO/cJPPt95sCtlvi2MkS75J5OVt//G1PD8K4OJlmfpWyX0JWu0MUdIX4NZTZTPldlNmU2OOSOwfazXcxNBroPF9Htg/6NLr4XWzvWVTitI5KAiyNmwEGnYjQosbmgspz2tDxA62GegvKlEuWu/qkxjryEFatv2aeGEOm+IRkJ/ikcIojHtJvNfLnMI1A/NAQe3XLjJ9iPuwQPNgCWHcxkzT9ugbpdS7IzP39HZc3f/T1EQHByT0M1Me/4m4eWnrLMB8UseZzVhr2viTOlPpsiMnaEAka8MnpyaShR/ahlYdm7zJjBW+EosEwyrjO2KV67iYefowDoXd6V0lHaCYhlc2fsxy/cc1UgkggsqGwtiPdzhRVfe9kW6NRXTwQJugGWO0/ZG+9bpY3/qIy9Hy7P7f2Xd5vt70Z/L2VLyNR9TeA/ldjfn7fEY6o+ZEfsIhUNrG442DaovLU6bX9dDU1p0AXAIF9UBNqOH9LVNwqswamIgHF8uZbtuZe/9IlTATb49PIemzmrTbxFg="

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
- go test .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t $DOCKER_REPO . ;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPO;
    fi
